name: Docker Image CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          sudo apt-get update
          sudo apt-get -y install skopeo
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shanghai.aliyuncs.com
          # 使用Dockerfile构建镜像
          pwd
          ls -alh
          # cat ./current_image_list.txt
          # bash ./sync.sh
          for image in `cat ./current_image_list.txt`
          do
             echo $image
             tag=`./sha256_amd64 $image`
             skopeo copy  docker://${image} docker://registry.cn-shanghai.aliyuncs.com/shuaiyy/2233:${tag}  \
             --dest-creds "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}"
             # --dest-username=${{ secrets.DOCKER_USERNAME }} --dest-password=${{ secrets.DOCKER_PASSWORD }}
          done